# Generated by Django 4.2.7 on 2024-07-23 15:40

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('nro_circuito', models.AutoField(primary_key=True, serialize=False)),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('nro_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=255)),
                ('norma', models.CharField(max_length=255)),
                ('arancel', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('area_tematica', models.CharField(choices=[('durabilidad', 'Durabilidad'), ('ensayos_mecanicos', 'Ensayos Mecánicos'), ('geologia', 'Geología'), ('hormigones', 'Hormigones'), ('metalurgia', 'Metalurgia'), ('patrimonio', 'Patrimonio'), ('quimica', 'Química'), ('tecnologia_vial', 'Tecnología Vial'), ('estudios_especiales', 'Estudios Especiales'), ('servicios_tecnologicos', 'Servicios Tecnológicos'), ('direccion', 'Dirección')])),
                ('modulo', models.IntegerField(default=275, validators=[django.core.validators.MaxValueValidator(999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('nro_solicitante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_solicitante', models.CharField(max_length=255)),
                ('cuit', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('codigoPostal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudInterarea',
            fields=[
                ('nro_solicitudInterarea', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitudInterarea', models.DateField()),
                ('areaTematica_origen', models.CharField(choices=[('durabilidad', 'Durabilidad'), ('ensayos_mecanicos', 'Ensayos Mecánicos'), ('geologia', 'Geología'), ('hormigones', 'Hormigones'), ('metalurgia', 'Metalurgia'), ('patrimonio', 'Patrimonio'), ('quimica', 'Química'), ('tecnologia_vial', 'Tecnología Vial'), ('estudios_especiales', 'Estudios Especiales'), ('servicios_tecnologicos', 'Servicios Tecnológicos'), ('direccion', 'Dirección')])),
                ('inter_areaTematica', models.CharField(choices=[('durabilidad', 'Durabilidad'), ('ensayos_mecanicos', 'Ensayos Mecánicos'), ('geologia', 'Geología'), ('hormigones', 'Hormigones'), ('metalurgia', 'Metalurgia'), ('patrimonio', 'Patrimonio'), ('quimica', 'Química'), ('tecnologia_vial', 'Tecnología Vial'), ('estudios_especiales', 'Estudios Especiales'), ('servicios_tecnologicos', 'Servicios Tecnológicos'), ('direccion', 'Dirección')])),
                ('muestras_solicitudIa', models.TextField()),
                ('num_labs', models.CharField(null=True)),
                ('observaciones', models.TextField(max_length=255, null=True)),
                ('completo', models.BooleanField(default=False)),
                ('nro_circuito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('nro_recepcion', models.AutoField(primary_key=True, serialize=False)),
                ('nros_remitos', models.CharField(max_length=255, null=True)),
                ('estado_recepcion', models.CharField(choices=[('sin_llegar', 'Sin LLegar'), ('parcial', 'Parcial'), ('total', 'Total')], default='sin_llegar')),
                ('plazo_muestras', models.IntegerField(default=30)),
                ('completo', models.BooleanField(default=False)),
                ('nro_circuito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('nro_presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_presupuesto', models.DateField()),
                ('contacto', models.CharField(max_length=100)),
                ('telefono2', models.CharField(max_length=20, null=True)),
                ('email2', models.EmailField(max_length=50, null=True)),
                ('area_tematica', models.CharField(choices=[('durabilidad', 'Durabilidad'), ('ensayos_mecanicos', 'Ensayos Mecánicos'), ('geologia', 'Geología'), ('hormigones', 'Hormigones'), ('metalurgia', 'Metalurgia'), ('patrimonio', 'Patrimonio'), ('quimica', 'Química'), ('tecnologia_vial', 'Tecnología Vial'), ('estudios_especiales', 'Estudios Especiales'), ('servicios_tecnologicos', 'Servicios Tecnológicos'), ('direccion', 'Dirección')])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')])),
                ('arancel_presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(max_length=255, null=True)),
                ('estado_presupuesto', models.CharField(choices=[('en_espera', 'En Espera'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('modificado', 'Modificado'), ('actualizado', 'Actualizado')])),
                ('nro_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.solicitante')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('nro_ordenServicio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ordenServicio', models.DateField()),
                ('observaciones', models.TextField(max_length=255, null=True)),
                ('completo', models.BooleanField(default=False)),
                ('nro_circuito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito')),
            ],
        ),
        migrations.CreateModel(
            name='Legajo',
            fields=[
                ('nro_legajo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_legajo', models.DateField()),
                ('rangos_laboratorios', models.CharField(max_length=255)),
                ('pago', models.CharField(choices=[(0, '0%'), (50, '50%'), (100, '100%')])),
                ('plazo_pago', models.IntegerField(default=30)),
                ('adjunto_factura', models.FileField(null=True, upload_to='facturas/')),
                ('completo', models.BooleanField(default=False)),
                ('nro_circuito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito')),
            ],
        ),
        migrations.CreateModel(
            name='InformeServicio',
            fields=[
                ('nro_informeServicio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_informeServicio', models.DateField(default=datetime.date.today)),
                ('adjunto_informeServicio', models.FileField(upload_to='informes_servicio/')),
                ('revision', models.BooleanField(default=False)),
                ('firma_area', models.BooleanField(default=False)),
                ('firma_direccion', models.BooleanField(default=False)),
                ('completo', models.BooleanField(default=False)),
                ('nro_circuito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito')),
            ],
        ),
        migrations.CreateModel(
            name='InformeInterarea',
            fields=[
                ('nro_informeInterarea', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_informeInterarea', models.DateField()),
                ('adjunto_informeInterarea', models.FileField(upload_to='informes_interarea/')),
                ('nro_circuito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito')),
                ('nro_solicitudInterarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.solicitudinterarea')),
            ],
        ),
        migrations.CreateModel(
            name='InformeArea',
            fields=[
                ('nro_informeArea', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_informeArea', models.DateField()),
                ('adjunto_informeArea', models.FileField(upload_to='informes_areas/')),
                ('completo', models.BooleanField(default=False)),
                ('estado_informeArea', models.CharField(choices=[('sin_informe', 'Sin Informe'), ('parcial', 'Parcial'), ('total', 'Total')], default='sin_informe')),
                ('nro_circuito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('nro_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cant', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nro_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.presupuesto')),
                ('nro_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInterarea',
            fields=[
                ('nro_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cant', models.IntegerField()),
                ('nro_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.servicio')),
                ('nro_solicitudInterarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.solicitudinterarea')),
            ],
        ),
        migrations.CreateModel(
            name='DataServicio',
            fields=[
                ('nro_dataServicio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_dataServicio', models.DateField()),
                ('adjunto_solicitudServicio', models.FileField(null=True, upload_to='solicitudes_servicio/')),
                ('obra', models.CharField(max_length=255, null=True)),
                ('plazo_estimado', models.IntegerField()),
                ('cant_numLabs', models.IntegerField()),
                ('muestras', models.TextField()),
                ('observaciones', models.TextField(max_length=255, null=True)),
                ('completo', models.BooleanField(default=False)),
                ('finalizado', models.BooleanField(default=False)),
                ('nro_circuito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito')),
                ('nro_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.presupuesto')),
            ],
        ),
    ]
