# Generated by Django 4.2.7 on 2023-12-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legajo',
            name='num_laboratorios',
        ),
        migrations.AddField(
            model_name='legajo',
            name='rangos_laboratorios',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legajo',
            name='ultimo_numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dataservicio',
            name='area_tematica',
            field=models.CharField(choices=[('durabilidad', 'Durabilidad'), ('ensayos_mecanicos', 'Ensayos Mecánicos'), ('geologia', 'Geología'), ('hormigones', 'Hormigones'), ('metalurgia', 'Metalurgia'), ('patrimonio', 'Patrimonio'), ('quimica', 'Química'), ('tecnologia_vial', 'Tecnología Vial'), ('estudios_especiales', 'Estudios Especiales'), ('servicios_tecnologicos', 'Servicios Tecnológicos'), ('direccion', 'Dirección')]),
        ),
        migrations.AlterField(
            model_name='informeinterarea',
            name='area_tematica',
            field=models.CharField(choices=[('durabilidad', 'Durabilidad'), ('ensayos_mecanicos', 'Ensayos Mecánicos'), ('geologia', 'Geología'), ('hormigones', 'Hormigones'), ('metalurgia', 'Metalurgia'), ('patrimonio', 'Patrimonio'), ('quimica', 'Química'), ('tecnologia_vial', 'Tecnología Vial'), ('estudios_especiales', 'Estudios Especiales'), ('servicios_tecnologicos', 'Servicios Tecnológicos'), ('direccion', 'Dirección')]),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='area_tematica',
            field=models.CharField(choices=[('durabilidad', 'Durabilidad'), ('ensayos_mecanicos', 'Ensayos Mecánicos'), ('geologia', 'Geología'), ('hormigones', 'Hormigones'), ('metalurgia', 'Metalurgia'), ('patrimonio', 'Patrimonio'), ('quimica', 'Química'), ('tecnologia_vial', 'Tecnología Vial'), ('estudios_especiales', 'Estudios Especiales'), ('servicios_tecnologicos', 'Servicios Tecnológicos'), ('direccion', 'Dirección')]),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='estado_presupuesto',
            field=models.CharField(choices=[('en_espera', 'En Espera'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('modificado', 'Modificado'), ('actualizado', 'Actualizado')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='area_tematica',
            field=models.CharField(choices=[('durabilidad', 'Durabilidad'), ('ensayos_mecanicos', 'Ensayos Mecánicos'), ('geologia', 'Geología'), ('hormigones', 'Hormigones'), ('metalurgia', 'Metalurgia'), ('patrimonio', 'Patrimonio'), ('quimica', 'Química'), ('tecnologia_vial', 'Tecnología Vial'), ('estudios_especiales', 'Estudios Especiales'), ('servicios_tecnologicos', 'Servicios Tecnológicos'), ('direccion', 'Dirección')]),
        ),
        migrations.AlterField(
            model_name='solicitudinterarea',
            name='area_tematica',
            field=models.CharField(choices=[('durabilidad', 'Durabilidad'), ('ensayos_mecanicos', 'Ensayos Mecánicos'), ('geologia', 'Geología'), ('hormigones', 'Hormigones'), ('metalurgia', 'Metalurgia'), ('patrimonio', 'Patrimonio'), ('quimica', 'Química'), ('tecnologia_vial', 'Tecnología Vial'), ('estudios_especiales', 'Estudios Especiales'), ('servicios_tecnologicos', 'Servicios Tecnológicos'), ('direccion', 'Dirección')]),
        ),
    ]
