# Generated by Django 5.0.7 on 2024-07-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_modulohistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimoNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2024)),
                ('ultimo_numero', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='dataservicio',
            name='obra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataservicio',
            name='observaciones',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='observaciones',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='email2',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='observaciones',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='telefono2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='nros_remitos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudinterarea',
            name='num_labs',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudinterarea',
            name='observaciones',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
