# Generated by Django 4.2.7 on 2024-02-05 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_legajo_num_laboratorios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='arancel',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
