# Generated by Django 5.0.7 on 2024-07-31 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_ultimonumero_alter_dataservicio_obra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor', models.IntegerField(default=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='ModuloHistory',
        ),
    ]
