# Generated by Django 4.2.7 on 2024-02-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_servicio_arancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataservicio',
            name='area_tematica',
        ),
        migrations.RemoveField(
            model_name='dataservicio',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='dataservicio',
            name='nro_legajo',
        ),
        migrations.RemoveField(
            model_name='dataservicio',
            name='telefono',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='telefono2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
