# Generated by Django 4.2.7 on 2024-02-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_dataservicio_area_tematica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='email',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='email2',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dataservicio',
            name='observaciones',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='observaciones',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='contacto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='observaciones',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudinterarea',
            name='observaciones',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
