# Generated by Django 4.2.7 on 2024-09-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='informeservicio',
            name='revisiones',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
