# Generated by Django 4.2.7 on 2024-02-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_presupuesto_email_presupuesto_email2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataservicio',
            name='obra',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
