# Generated by Django 4.2.7 on 2024-02-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_dataservicio_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataservicio',
            name='adjunto_solicitudServicio',
            field=models.FileField(null=True, upload_to='solicitudes_servicio/'),
        ),
    ]
