# Generated by Django 4.2.7 on 2024-09-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_informeservicio_corregir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informeservicio',
            old_name='revisiones',
            new_name='correcciones',
        ),
    ]
