# Generated by Django 4.2.7 on 2024-10-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename_revisiones_informeservicio_correcciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='informearea',
            name='registros_ensayo',
            field=models.FileField(null=True, upload_to='registros_ensayo/'),
        ),
    ]
