# Generated by Django 4.2.7 on 2024-02-24 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename_adjunto_informeservicio_informearea_adjunto_informearea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legajo',
            name='nro_dataServicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='modulo',
            field=models.IntegerField(default=275, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
