# Generated by Django 4.2.7 on 2024-02-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_legajo_nro_dataservicio_servicio_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('nro_circuito', models.AutoField(primary_key=True, serialize=False)),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='dataservicio',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informearea',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informeservicio',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legajo',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='legajo',
            name='pago',
            field=models.CharField(choices=[(0, '0%'), (50, '50%'), (100, '100%')]),
        ),
    ]
