# Generated by Django 4.2.7 on 2024-10-02 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_informearea_registros_ensayo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_parcial', models.DateField(auto_now_add=True)),
                ('adjunto_parcial', models.FileField(upload_to='informes_parciales/')),
                ('informe_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_parciales', to='database.informearea')),
            ],
        ),
    ]
