# Generated by Django 4.2.7 on 2024-02-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_circuito_dataservicio_completo_informearea_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataservicio',
            name='nro_circuito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito'),
        ),
        migrations.AddField(
            model_name='informearea',
            name='nro_circuito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito'),
        ),
        migrations.AddField(
            model_name='informeinterarea',
            name='nro_circuito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito'),
        ),
        migrations.AddField(
            model_name='informeservicio',
            name='nro_circuito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito'),
        ),
        migrations.AddField(
            model_name='legajo',
            name='nro_circuito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='nro_circuito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='nro_circuito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito'),
        ),
        migrations.AddField(
            model_name='solicitudinterarea',
            name='nro_circuito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.circuito'),
        ),
    ]
