# Generated by Django 4.2.7 on 2024-10-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_informeparcial_nro_circuito'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformeParcial',
            new_name='InformeAreaParcial',
        ),
    ]
