# Generated by Django 4.2.7 on 2024-02-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_dataservicio_nro_circuito_informearea_nro_circuito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataservicio',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
