# Generated by Django 4.2.7 on 2024-02-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_dataservicio_finalizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataservicio',
            old_name='fecha',
            new_name='fecha_dataServicio',
        ),
        migrations.RenameField(
            model_name='informearea',
            old_name='fecha',
            new_name='fecha_informeArea',
        ),
        migrations.RenameField(
            model_name='informeinterarea',
            old_name='fecha',
            new_name='fecha_informeInterarea',
        ),
        migrations.RenameField(
            model_name='informeservicio',
            old_name='fecha',
            new_name='fecha_informeServicio',
        ),
        migrations.RenameField(
            model_name='legajo',
            old_name='fecha',
            new_name='fecha_legajo',
        ),
        migrations.RenameField(
            model_name='ordenservicio',
            old_name='fecha',
            new_name='fecha_ordenServicio',
        ),
        migrations.RenameField(
            model_name='presupuesto',
            old_name='fecha',
            new_name='fecha_presupuesto',
        ),
        migrations.RenameField(
            model_name='solicitudinterarea',
            old_name='fecha',
            new_name='fecha_solicitudInterarea',
        ),
    ]
