# Generated by Django 4.2.7 on 2024-02-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_rename_fecha_dataservicio_fecha_dataservicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudinterarea',
            old_name='area_tematica',
            new_name='inter_areaTematica',
        ),
    ]
