# Generated by Django 4.2.7 on 2024-02-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_rename_area_tematica_solicitudinterarea_inter_areatematica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legajo',
            name='facturaAdjunta',
        ),
        migrations.RemoveField(
            model_name='legajo',
            name='nro_ordenServicio',
        ),
        migrations.RemoveField(
            model_name='legajo',
            name='nro_recepcion',
        ),
    ]
