# Generated by Django 4.2.7 on 2024-02-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_remove_legajo_facturaadjunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informearea',
            name='estado_informeArea',
            field=models.CharField(choices=[('sin_informe', 'Sin Informe'), ('parcial', 'Parcial'), ('total', 'Total')], default='sin_informe'),
        ),
    ]
