# Generated by Django 4.2.7 on 2024-02-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_alter_legajo_adjunto_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informearea',
            name='nro_informeServicio',
        ),
        migrations.RemoveField(
            model_name='informearea',
            name='nro_ordenServicio',
        ),
        migrations.RemoveField(
            model_name='informearea',
            name='nro_solicitud_interarea',
        ),
        migrations.RemoveField(
            model_name='informeservicio',
            name='nro_informeArea',
        ),
        migrations.RemoveField(
            model_name='ordenservicio',
            name='nro_informeArea',
        ),
        migrations.RemoveField(
            model_name='ordenservicio',
            name='nro_legajo',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='nro_legajo',
        ),
        migrations.RemoveField(
            model_name='solicitudinterarea',
            name='nro_informeInterarea',
        ),
    ]
