# Generated by Django 4.2.7 on 2024-03-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_remove_informearea_nro_informeservicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='estado_recepcion',
            field=models.CharField(choices=[('sin_llegar', 'Sin LLegar'), ('parcial', 'Parcial'), ('total', 'Total')], default='sin_llegar'),
        ),
    ]
