# Generated by Django 4.2.7 on 2024-03-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_alter_recepcion_estado_recepcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legajo',
            name='ultimo_numero',
        ),
        migrations.AlterField(
            model_name='legajo',
            name='adjunto_factura',
            field=models.FileField(null=True, upload_to='facturas/'),
        ),
    ]
