# Generated by Django 4.2.7 on 2024-07-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_remove_legajo_ultimo_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudinterarea',
            name='adjunto_solicitudInterarea',
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='nros_remitos',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
