"""
Django settings for cle_backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta


<<<<<<< HEAD
# Base directory of the project
=======
# Build paths inside the project like this: BASE_DIR / 'subdir'.
>>>>>>> inicializacion-pc-lemit
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_i8)8l-gu_vvki9p!081t1un+ch5lncck)xx#6yob*f=4t72o9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

<<<<<<< HEAD
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'localhost:8080']
=======
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'localhost:8080', 'cle-lemit.local',]
>>>>>>> inicializacion-pc-lemit


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'database',
    'aranceles',
    'solicitantes',
    'presupuestos',
    'encurso',
    'authentication',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cle_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<< HEAD
        'DIRS': [
            BASE_DIR / 'templates', 
            BASE_DIR / 'aranceles' / 'templates'
        ],
=======
        'DIRS': [BASE_DIR / 'aranceles' / 'templates'],
>>>>>>> inicializacion-pc-lemit
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                'rest_framework.templatetags.rest_framework',
            ],
        },
    },
]

# Configuración de Django REST framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework.renderers.JSONRenderer',
    ],
}

SIMPLE_JWT = {
<<<<<<< HEAD
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=180),
=======
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
>>>>>>> inicializacion-pc-lemit
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

WSGI_APPLICATION = 'cle_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'cle_database',
        'USER': 'postgres',
<<<<<<< HEAD
        'PASSWORD': '5uperpostgre5',
=======
        'PASSWORD': '5uperposgre5',
>>>>>>> inicializacion-pc-lemit
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

<<<<<<< HEAD
MEDIA_URL = '/media/'
=======
>>>>>>> inicializacion-pc-lemit

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

<<<<<<< HEAD
STATIC_URL = '/static/'

# Ruta donde Django buscará los archivos estáticos durante el desarrollo
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Ruta donde Django recopilará los archivos estáticos cuando se ejecute 'collectstatic'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Ruta para archivos estáticos recolectados

=======
STATIC_URL = 'static/'
>>>>>>> inicializacion-pc-lemit

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuración de registro
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',  # Cambia el nivel a DEBUG para ver mensajes de depuración
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',  # Cambia el nivel a DEBUG para ver mensajes de depuración
            'propagate': True,
        },
    },
}

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8080',
<<<<<<< HEAD
=======
    'http://cle-lemit.local',
>>>>>>> inicializacion-pc-lemit
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8080',
    'https://localhost:8080',
<<<<<<< HEAD
=======
    'http://cle-lemit.local',

>>>>>>> inicializacion-pc-lemit
]

CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

APPEND_SLASH = False